/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as UserRouteRouteImport } from './routes/_user/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as UserSubmitFriendLinkRouteImport } from './routes/_user/submit-friend-link'
import { Route as PublicUnsubscribeRouteImport } from './routes/_public/unsubscribe'
import { Route as PublicTimelineRouteImport } from './routes/_public/timeline'
import { Route as PublicSearchRouteImport } from './routes/_public/search'
import { Route as PublicProjectsRouteImport } from './routes/_public/projects'
import { Route as PublicPostsRouteImport } from './routes/_public/posts'
import { Route as PublicPhotowallRouteImport } from './routes/_public/photowall'
import { Route as PublicMusicRouteImport } from './routes/_public/music'
import { Route as PublicMomentsRouteImport } from './routes/_public/moments'
import { Route as PublicFriendLinksRouteImport } from './routes/_public/friend-links'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthResetLinkRouteImport } from './routes/_auth/reset-link'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AdminPostsRouteRouteImport } from './routes/admin/posts/route'
import { Route as AdminTagsIndexRouteImport } from './routes/admin/tags/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminPostsIndexRouteImport } from './routes/admin/posts/index'
import { Route as AdminMediaIndexRouteImport } from './routes/admin/media/index'
import { Route as AdminFriendLinksIndexRouteImport } from './routes/admin/friend-links/index'
import { Route as AdminCommentsIndexRouteImport } from './routes/admin/comments/index'
import { Route as PublicPostSlugRouteImport } from './routes/_public/post/$slug'
import { Route as AdminPostsEditIdRouteImport } from './routes/admin/posts/edit.$id'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRouteRoute = UserRouteRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSubmitFriendLinkRoute = UserSubmitFriendLinkRouteImport.update({
  id: '/submit-friend-link',
  path: '/submit-friend-link',
  getParentRoute: () => UserRouteRoute,
} as any)
const PublicUnsubscribeRoute = PublicUnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicTimelineRoute = PublicTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSearchRoute = PublicSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicProjectsRoute = PublicProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPostsRoute = PublicPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPhotowallRoute = PublicPhotowallRouteImport.update({
  id: '/photowall',
  path: '/photowall',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicMusicRoute = PublicMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicMomentsRoute = PublicMomentsRouteImport.update({
  id: '/moments',
  path: '/moments',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicFriendLinksRoute = PublicFriendLinksRouteImport.update({
  id: '/friend-links',
  path: '/friend-links',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetLinkRoute = AuthResetLinkRouteImport.update({
  id: '/reset-link',
  path: '/reset-link',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminPostsRouteRoute = AdminPostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTagsIndexRoute = AdminTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPostsRouteRoute,
} as any)
const AdminMediaIndexRoute = AdminMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFriendLinksIndexRoute = AdminFriendLinksIndexRouteImport.update({
  id: '/friend-links/',
  path: '/friend-links/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommentsIndexRoute = AdminCommentsIndexRouteImport.update({
  id: '/comments/',
  path: '/comments/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicPostSlugRoute = PublicPostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminPostsEditIdRoute = AdminPostsEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminPostsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/posts': typeof AdminPostsRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-link': typeof AuthResetLinkRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/about': typeof PublicAboutRoute
  '/friend-links': typeof PublicFriendLinksRoute
  '/moments': typeof PublicMomentsRoute
  '/music': typeof PublicMusicRoute
  '/photowall': typeof PublicPhotowallRoute
  '/posts': typeof PublicPostsRoute
  '/projects': typeof PublicProjectsRoute
  '/search': typeof PublicSearchRoute
  '/timeline': typeof PublicTimelineRoute
  '/unsubscribe': typeof PublicUnsubscribeRoute
  '/submit-friend-link': typeof UserSubmitFriendLinkRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/admin/': typeof AdminIndexRoute
  '/post/$slug': typeof PublicPostSlugRoute
  '/admin/comments/': typeof AdminCommentsIndexRoute
  '/admin/friend-links/': typeof AdminFriendLinksIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/tags/': typeof AdminTagsIndexRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-link': typeof AuthResetLinkRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/about': typeof PublicAboutRoute
  '/friend-links': typeof PublicFriendLinksRoute
  '/moments': typeof PublicMomentsRoute
  '/music': typeof PublicMusicRoute
  '/photowall': typeof PublicPhotowallRoute
  '/posts': typeof PublicPostsRoute
  '/projects': typeof PublicProjectsRoute
  '/search': typeof PublicSearchRoute
  '/timeline': typeof PublicTimelineRoute
  '/unsubscribe': typeof PublicUnsubscribeRoute
  '/submit-friend-link': typeof UserSubmitFriendLinkRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/admin': typeof AdminIndexRoute
  '/post/$slug': typeof PublicPostSlugRoute
  '/admin/comments': typeof AdminCommentsIndexRoute
  '/admin/friend-links': typeof AdminFriendLinksIndexRoute
  '/admin/media': typeof AdminMediaIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/tags': typeof AdminTagsIndexRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_user': typeof UserRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/posts': typeof AdminPostsRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-link': typeof AuthResetLinkRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/friend-links': typeof PublicFriendLinksRoute
  '/_public/moments': typeof PublicMomentsRoute
  '/_public/music': typeof PublicMusicRoute
  '/_public/photowall': typeof PublicPhotowallRoute
  '/_public/posts': typeof PublicPostsRoute
  '/_public/projects': typeof PublicProjectsRoute
  '/_public/search': typeof PublicSearchRoute
  '/_public/timeline': typeof PublicTimelineRoute
  '/_public/unsubscribe': typeof PublicUnsubscribeRoute
  '/_user/submit-friend-link': typeof UserSubmitFriendLinkRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/post/$slug': typeof PublicPostSlugRoute
  '/admin/comments/': typeof AdminCommentsIndexRoute
  '/admin/friend-links/': typeof AdminFriendLinksIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/tags/': typeof AdminTagsIndexRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/posts'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-link'
    | '/verify-email'
    | '/about'
    | '/friend-links'
    | '/moments'
    | '/music'
    | '/photowall'
    | '/posts'
    | '/projects'
    | '/search'
    | '/timeline'
    | '/unsubscribe'
    | '/submit-friend-link'
    | '/oauth/consent'
    | '/admin/'
    | '/post/$slug'
    | '/admin/comments/'
    | '/admin/friend-links/'
    | '/admin/media/'
    | '/admin/posts/'
    | '/admin/settings/'
    | '/admin/tags/'
    | '/admin/posts/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-link'
    | '/verify-email'
    | '/about'
    | '/friend-links'
    | '/moments'
    | '/music'
    | '/photowall'
    | '/posts'
    | '/projects'
    | '/search'
    | '/timeline'
    | '/unsubscribe'
    | '/submit-friend-link'
    | '/oauth/consent'
    | '/admin'
    | '/post/$slug'
    | '/admin/comments'
    | '/admin/friend-links'
    | '/admin/media'
    | '/admin/posts'
    | '/admin/settings'
    | '/admin/tags'
    | '/admin/posts/edit/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/_user'
    | '/admin'
    | '/admin/posts'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-link'
    | '/_auth/verify-email'
    | '/_public/about'
    | '/_public/friend-links'
    | '/_public/moments'
    | '/_public/music'
    | '/_public/photowall'
    | '/_public/posts'
    | '/_public/projects'
    | '/_public/search'
    | '/_public/timeline'
    | '/_public/unsubscribe'
    | '/_user/submit-friend-link'
    | '/oauth/consent'
    | '/_public/'
    | '/admin/'
    | '/_public/post/$slug'
    | '/admin/comments/'
    | '/admin/friend-links/'
    | '/admin/media/'
    | '/admin/posts/'
    | '/admin/settings/'
    | '/admin/tags/'
    | '/admin/posts/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  OauthConsentRoute: typeof OauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/submit-friend-link': {
      id: '/_user/submit-friend-link'
      path: '/submit-friend-link'
      fullPath: '/submit-friend-link'
      preLoaderRoute: typeof UserSubmitFriendLinkRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_public/unsubscribe': {
      id: '/_public/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof PublicUnsubscribeRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/timeline': {
      id: '/_public/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof PublicTimelineRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/search': {
      id: '/_public/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof PublicSearchRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/projects': {
      id: '/_public/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof PublicProjectsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/posts': {
      id: '/_public/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PublicPostsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/photowall': {
      id: '/_public/photowall'
      path: '/photowall'
      fullPath: '/photowall'
      preLoaderRoute: typeof PublicPhotowallRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/music': {
      id: '/_public/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof PublicMusicRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/moments': {
      id: '/_public/moments'
      path: '/moments'
      fullPath: '/moments'
      preLoaderRoute: typeof PublicMomentsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/friend-links': {
      id: '/_public/friend-links'
      path: '/friend-links'
      fullPath: '/friend-links'
      preLoaderRoute: typeof PublicFriendLinksRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-link': {
      id: '/_auth/reset-link'
      path: '/reset-link'
      fullPath: '/reset-link'
      preLoaderRoute: typeof AuthResetLinkRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tags/': {
      id: '/admin/tags/'
      path: '/tags'
      fullPath: '/admin/tags/'
      preLoaderRoute: typeof AdminTagsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminPostsRouteRoute
    }
    '/admin/media/': {
      id: '/admin/media/'
      path: '/media'
      fullPath: '/admin/media/'
      preLoaderRoute: typeof AdminMediaIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/friend-links/': {
      id: '/admin/friend-links/'
      path: '/friend-links'
      fullPath: '/admin/friend-links/'
      preLoaderRoute: typeof AdminFriendLinksIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/comments/': {
      id: '/admin/comments/'
      path: '/comments'
      fullPath: '/admin/comments/'
      preLoaderRoute: typeof AdminCommentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/post/$slug': {
      id: '/_public/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof PublicPostSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/admin/posts/edit/$id': {
      id: '/admin/posts/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/posts/edit/$id'
      preLoaderRoute: typeof AdminPostsEditIdRouteImport
      parentRoute: typeof AdminPostsRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetLinkRoute: typeof AuthResetLinkRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetLinkRoute: AuthResetLinkRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicFriendLinksRoute: typeof PublicFriendLinksRoute
  PublicMomentsRoute: typeof PublicMomentsRoute
  PublicMusicRoute: typeof PublicMusicRoute
  PublicPhotowallRoute: typeof PublicPhotowallRoute
  PublicPostsRoute: typeof PublicPostsRoute
  PublicProjectsRoute: typeof PublicProjectsRoute
  PublicSearchRoute: typeof PublicSearchRoute
  PublicTimelineRoute: typeof PublicTimelineRoute
  PublicUnsubscribeRoute: typeof PublicUnsubscribeRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicPostSlugRoute: typeof PublicPostSlugRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicFriendLinksRoute: PublicFriendLinksRoute,
  PublicMomentsRoute: PublicMomentsRoute,
  PublicMusicRoute: PublicMusicRoute,
  PublicPhotowallRoute: PublicPhotowallRoute,
  PublicPostsRoute: PublicPostsRoute,
  PublicProjectsRoute: PublicProjectsRoute,
  PublicSearchRoute: PublicSearchRoute,
  PublicTimelineRoute: PublicTimelineRoute,
  PublicUnsubscribeRoute: PublicUnsubscribeRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicPostSlugRoute: PublicPostSlugRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface UserRouteRouteChildren {
  UserSubmitFriendLinkRoute: typeof UserSubmitFriendLinkRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserSubmitFriendLinkRoute: UserSubmitFriendLinkRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

interface AdminPostsRouteRouteChildren {
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  AdminPostsEditIdRoute: typeof AdminPostsEditIdRoute
}

const AdminPostsRouteRouteChildren: AdminPostsRouteRouteChildren = {
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  AdminPostsEditIdRoute: AdminPostsEditIdRoute,
}

const AdminPostsRouteRouteWithChildren = AdminPostsRouteRoute._addFileChildren(
  AdminPostsRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminPostsRouteRoute: typeof AdminPostsRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCommentsIndexRoute: typeof AdminCommentsIndexRoute
  AdminFriendLinksIndexRoute: typeof AdminFriendLinksIndexRoute
  AdminMediaIndexRoute: typeof AdminMediaIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminTagsIndexRoute: typeof AdminTagsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminPostsRouteRoute: AdminPostsRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminCommentsIndexRoute: AdminCommentsIndexRoute,
  AdminFriendLinksIndexRoute: AdminFriendLinksIndexRoute,
  AdminMediaIndexRoute: AdminMediaIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminTagsIndexRoute: AdminTagsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  OauthConsentRoute: OauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
